<?php

namespace Ais\KabupatenBundle\Repository;

/**
 * KabupatenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KabupatenRepository extends \Doctrine\ORM\EntityRepository
{
}
